### ISSUE TITLE
I have problem running on OpenBSD/adJ 5.8

### ISSUE THREAD

**Issue by vtamara** [johnae/sambal#24]
When running 

```
require 'sambal' 

client = Sambal::Client.new(domain: 'domain', host: '192.168.1.1', share: 'share', user: 'user', password: 'pass', port: 445)
```

It produces

```
/usr/local/lib/ruby/gems/2.3/gems/sambal-0.1.7/lib/sambal/client.rb:39:in `rescue in initialize': Unknown Process Failed!! (can't get Master/Slave device): "can't get Master/Slave device" (RuntimeError)
/usr/local/lib/ruby/gems/2.3/gems/sambal-0.1.7/lib/sambal/client.rb:16:in `spawn'
/usr/local/lib/ruby/gems/2.3/gems/sambal-0.1.7/lib/sambal/client.rb:16:in `initialize'
herram/pruebasambal.rb:7:in `new'
herram/pruebasambal.rb:7:in `<main>'
        from /usr/local/lib/ruby/gems/2.3/gems/sambal-0.1.7/lib/sambal/client.rb:13:in `initialize'
        from herram/pruebasambal.rb:3:in `new'
        from herram/pruebasambal.rb:3:in `<main>'
```

I guess it has to do more with the ruby interpreter on my platform.

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-openbsd]
```

**Comment by johnae** [comment]
Sorry for the late reply. Busy at work. I'm on Linux myself, I know it works on OS X. Haven't tested the BSD:s I'm afraid. If you find the problem, please comment or create a pull request. Thanks.
