### ISSUE TITLE
`rescue in initialize': Unknown Process Failed!! (Input/output error - /dev/ttys002)

### ISSUE THREAD

**Issue by xbeta** [johnae/sambal#3]
Got this error when trying to use Sambal.  I believe it's related to the smbclient bug connecting via LDAP for authentication.

**code**
```ruby
require 'sambal'

client = Sambal::Client.new(domain: 'corp', host: '192.168.3.10', share: 'Releases', user: 'release-bot', password: '<masked>', port: 445)
client.ls
client.close # closes connection
```

**error log**
```ruby
Failed to connect
/Users/xbeta/.rvm/gems/ruby-1.9.3-p392/gems/sambal-0.1.2/lib/sambal.rb:73:in `rescue in initialize': Unknown Process Failed!! (Input/output error - /dev/ttys002): "Input/output error - /dev/ttys002" (RuntimeError)
/Users/xbeta/.rvm/gems/ruby-1.9.3-p392/gems/sambal-0.1.2/lib/sambal.rb:229:in `write'
/Users/xbeta/.rvm/gems/ruby-1.9.3-p392/gems/sambal-0.1.2/lib/sambal.rb:229:in `printf'
/Users/xbeta/.rvm/gems/ruby-1.9.3-p392/gems/sambal-0.1.2/lib/sambal.rb:229:in `close'
/Users/xbeta/.rvm/gems/ruby-1.9.3-p392/gems/sambal-0.1.2/lib/sambal.rb:69:in `initialize'
./publish_to_smb.rb:6:in `new'
./publish_to_smb.rb:6:in `<main>'
	from /Users/xbeta/.rvm/gems/ruby-1.9.3-p392/gems/sambal-0.1.2/lib/sambal.rb:46:in `initialize'
	from ./publish_to_smb.rb:6:in `new'
	from ./publish_to_smb.rb:6:in `<main>'
```

**Comment by johnae** [comment]
Since this is so old, I'll close it. Reopen if this is still a problem.
